# Generated by Django 4.0.4 on 2022-04-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField(max_length=30)),
                ('business_address', models.TextField(max_length=100)),
                ('business_website', models.SlugField(max_length=100)),
                ('venue_type', models.TextField(max_length=8)),
            ],
        ),
    ]
