# Generated by Django 4.0.4 on 2022-04-23 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.TextField(max_length=20)),
                ('promo_date', models.DateTimeField(verbose_name=datetime.datetime)),
                ('promo_description', models.CharField(max_length=100)),
            ],
        ),
    ]
